// 청첩장 템플릿 데이터
export const templates = [
  {
    id: 1,
    title: 'Modern Minimal',
    subtitle: '미니멀 모던',
    description: '깔끔하고 세련된 현대적 스타일',
    color: 'from-gray-900 via-gray-800 to-gray-900',
    accent: '#D4AF37',
    textColor: 'text-gray-100',
    bgStyle: 'bg-black',
    borderStyle: 'border-gray-700',
    shadowStyle: 'shadow-2xl shadow-gray-900/50',
    fontStyle: 'font-light tracking-wider',
    cardBg: 'bg-gradient-to-br from-gray-900 to-black',
    overlayEffect: 'backdrop-blur-sm',
    hoverEffect: 'hover:shadow-gold/20',
    icon: '💍'
  },
  {
    id: 2,
    title: 'Classic Elegant',
    subtitle: '클래식 엘레강트',
    description: '우아하고 고급스러운 전통적 스타일',
    color: 'from-blue-900 via-blue-800 to-indigo-900',
    accent: '#FFD700',
    textColor: 'text-amber-100',
    bgStyle: 'bg-gradient-to-br from-blue-950 to-indigo-950',
    borderStyle: 'border-amber-500/30',
    shadowStyle: 'shadow-xl shadow-blue-900/60',
    fontStyle: 'font-serif font-normal',
    cardBg: 'bg-gradient-to-t from-blue-950 via-blue-900 to-indigo-900',
    overlayEffect: 'bg-gradient-to-t from-black/20 to-transparent',
    hoverEffect: 'hover:shadow-amber-500/30',
    icon: '👑'
  },
  {
    id: 3,
    title: 'Nature Garden',
    subtitle: '네이처 가든',
    description: '자연스럽고 따뜻한 보태니컬 스타일',
    color: 'from-amber-50 via-orange-50 to-yellow-50',
    accent: '#8B7355',
    textColor: 'text-amber-900',
    bgStyle: 'bg-gradient-to-br from-amber-50 to-orange-100',
    borderStyle: 'border-amber-200',
    shadowStyle: 'shadow-lg shadow-amber-200/50',
    fontStyle: 'font-normal tracking-wide',
    cardBg: 'bg-[#FFF8F0]',
    overlayEffect: 'bg-gradient-to-b from-white/40 to-transparent',
    hoverEffect: 'hover:shadow-amber-300/50',
    icon: '🌿'
  },
  {
    id: 4,
    title: 'Vintage Romance',
    subtitle: '빈티지 로맨스',
    description: '로맨틱하고 감성적인 빈티지 스타일',
    color: 'from-pink-100 via-rose-100 to-pink-200',
    accent: '#D946A6',
    textColor: 'text-rose-900',
    bgStyle: 'bg-gradient-to-br from-pink-50 to-rose-100',
    borderStyle: 'border-pink-200',
    shadowStyle: 'shadow-xl shadow-pink-300/40',
    fontStyle: 'font-light italic',
    cardBg: 'bg-gradient-to-br from-pink-50 via-rose-50 to-pink-100',
    overlayEffect: 'backdrop-saturate-150',
    hoverEffect: 'hover:shadow-pink-400/50',
    icon: '💕'
  },
  {
    id: 5,
    title: 'Luxury Gold',
    subtitle: '럭셔리 골드',
    description: '화려하고 고급스러운 골드 스타일',
    color: 'from-yellow-50 via-amber-100 to-yellow-100',
    accent: '#D97706',
    textColor: 'text-amber-900',
    bgStyle: 'bg-gradient-to-br from-amber-100 to-yellow-200',
    borderStyle: 'border-amber-300',
    shadowStyle: 'shadow-2xl shadow-amber-400/50',
    fontStyle: 'font-semibold tracking-tight',
    cardBg: 'bg-gradient-to-br from-amber-50 via-yellow-100 to-amber-100',
    overlayEffect: 'bg-gradient-to-t from-amber-900/10 to-transparent',
    hoverEffect: 'hover:shadow-amber-500/60',
    icon: '✨'
  },
  {
    id: 6,
    title: 'Ocean Blue',
    subtitle: '오션 블루',
    description: '시원하고 모던한 블루 스타일',
    color: 'from-white via-blue-50 to-cyan-50',
    accent: '#0891b2',
    textColor: 'text-cyan-900',
    bgStyle: 'bg-gradient-to-br from-white to-blue-100',
    borderStyle: 'border-cyan-200',
    shadowStyle: 'shadow-lg shadow-cyan-300/40',
    fontStyle: 'font-normal tracking-normal',
    cardBg: 'bg-gradient-to-br from-white via-blue-50 to-cyan-100',
    overlayEffect: 'backdrop-brightness-110',
    hoverEffect: 'hover:shadow-cyan-400/50',
    icon: '🌊'
  },
  {
    id: 7,
    title: 'Pastel Dream',
    subtitle: '파스텔 드림',
    description: '부드럽고 사랑스러운 파스텔 스타일',
    color: 'from-purple-100 via-pink-100 to-blue-100',
    accent: '#A78BFA',
    textColor: 'text-purple-900',
    bgStyle: 'bg-gradient-to-br from-purple-50 to-pink-100',
    borderStyle: 'border-purple-200',
    shadowStyle: 'shadow-lg shadow-purple-300/40',
    fontStyle: 'font-light tracking-wide',
    cardBg: 'bg-gradient-to-br from-purple-50 via-pink-50 to-blue-50',
    overlayEffect: 'backdrop-saturate-125',
    hoverEffect: 'hover:shadow-purple-400/50',
    icon: '🦋'
  },
  {
    id: 8,
    title: 'Autumn Harvest',
    subtitle: '가을 하베스트',
    description: '따뜻한 가을 감성의 어스 톤 스타일',
    color: 'from-orange-100 via-red-100 to-yellow-100',
    accent: '#DC2626',
    textColor: 'text-orange-900',
    bgStyle: 'bg-gradient-to-br from-orange-100 to-red-100',
    borderStyle: 'border-orange-300',
    shadowStyle: 'shadow-xl shadow-orange-400/40',
    fontStyle: 'font-medium tracking-wide',
    cardBg: 'bg-gradient-to-br from-orange-50 via-amber-50 to-yellow-50',
    overlayEffect: 'bg-gradient-to-b from-white/30 to-transparent',
    hoverEffect: 'hover:shadow-orange-500/50',
    icon: '🍂'
  },
  {
    id: 9,
    title: 'Emerald Forest',
    subtitle: '에메랄드 포레스트',
    description: '깊고 우아한 그린 톤 스타일',
    color: 'from-emerald-800 via-green-700 to-teal-800',
    accent: '#10B981',
    textColor: 'text-emerald-100',
    bgStyle: 'bg-gradient-to-br from-emerald-900 to-teal-900',
    borderStyle: 'border-emerald-500/30',
    shadowStyle: 'shadow-xl shadow-emerald-900/60',
    fontStyle: 'font-normal tracking-wide',
    cardBg: 'bg-gradient-to-t from-emerald-950 via-emerald-900 to-teal-900',
    overlayEffect: 'bg-gradient-to-t from-black/30 to-transparent',
    hoverEffect: 'hover:shadow-emerald-500/40',
    icon: '🌲'
  },
  {
    id: 10,
    title: 'Monochrome Chic',
    subtitle: '모노크롬 시크',
    description: '흑백의 강렬하고 세련된 스타일',
    color: 'from-gray-100 via-white to-gray-200',
    accent: '#000000',
    textColor: 'text-gray-900',
    bgStyle: 'bg-gradient-to-br from-white to-gray-100',
    borderStyle: 'border-gray-300',
    shadowStyle: 'shadow-2xl shadow-gray-400/50',
    fontStyle: 'font-light tracking-widest',
    cardBg: 'bg-gradient-to-br from-white via-gray-50 to-gray-100',
    overlayEffect: 'backdrop-contrast-110',
    hoverEffect: 'hover:shadow-gray-500/50',
    icon: '◆'
  }
];

